# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParticleScanAnalysisWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblScanDataFilepath = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScanDataFilepath.sizePolicy().hasHeightForWidth())
        self.lblScanDataFilepath.setSizePolicy(sizePolicy)
        self.lblScanDataFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblScanDataFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblScanDataFilepath.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.lblScanDataFilepath.setScaledContents(False)
        self.lblScanDataFilepath.setWordWrap(False)
        self.lblScanDataFilepath.setObjectName("lblScanDataFilepath")
        self.horizontalLayout_2.addWidget(self.lblScanDataFilepath)
        self.txtScanDataFilepath = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtScanDataFilepath.sizePolicy().hasHeightForWidth())
        self.txtScanDataFilepath.setSizePolicy(sizePolicy)
        self.txtScanDataFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtScanDataFilepath.setObjectName("txtScanDataFilepath")
        self.horizontalLayout_2.addWidget(self.txtScanDataFilepath)
        self.btnScanDataSelect = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScanDataSelect.sizePolicy().hasHeightForWidth())
        self.btnScanDataSelect.setSizePolicy(sizePolicy)
        self.btnScanDataSelect.setMinimumSize(QtCore.QSize(100, 33))
        self.btnScanDataSelect.setMaximumSize(QtCore.QSize(100, 33))
        self.btnScanDataSelect.setObjectName("btnScanDataSelect")
        self.horizontalLayout_2.addWidget(self.btnScanDataSelect)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.grpBackgroundSubtraction = QtWidgets.QGroupBox(self.centralwidget)
        self.grpBackgroundSubtraction.setObjectName("grpBackgroundSubtraction")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grpBackgroundSubtraction)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblOutputFilepath = QtWidgets.QLabel(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOutputFilepath.sizePolicy().hasHeightForWidth())
        self.lblOutputFilepath.setSizePolicy(sizePolicy)
        self.lblOutputFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblOutputFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblOutputFilepath.setObjectName("lblOutputFilepath")
        self.horizontalLayout_4.addWidget(self.lblOutputFilepath)
        self.txtOutputFilepath = QtWidgets.QLineEdit(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtOutputFilepath.sizePolicy().hasHeightForWidth())
        self.txtOutputFilepath.setSizePolicy(sizePolicy)
        self.txtOutputFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtOutputFilepath.setObjectName("txtOutputFilepath")
        self.horizontalLayout_4.addWidget(self.txtOutputFilepath)
        self.btnOutputSelect = QtWidgets.QPushButton(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutputSelect.sizePolicy().hasHeightForWidth())
        self.btnOutputSelect.setSizePolicy(sizePolicy)
        self.btnOutputSelect.setMinimumSize(QtCore.QSize(100, 33))
        self.btnOutputSelect.setMaximumSize(QtCore.QSize(100, 33))
        self.btnOutputSelect.setObjectName("btnOutputSelect")
        self.horizontalLayout_4.addWidget(self.btnOutputSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnRun = QtWidgets.QPushButton(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRun.sizePolicy().hasHeightForWidth())
        self.btnRun.setSizePolicy(sizePolicy)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout.addWidget(self.btnRun)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.grpBackgroundSubtraction)
        self.grpSaveWithAxes = QtWidgets.QGroupBox(self.centralwidget)
        self.grpSaveWithAxes.setObjectName("grpSaveWithAxes")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.grpSaveWithAxes)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblOutputFilepathSWA = QtWidgets.QLabel(self.grpSaveWithAxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOutputFilepathSWA.sizePolicy().hasHeightForWidth())
        self.lblOutputFilepathSWA.setSizePolicy(sizePolicy)
        self.lblOutputFilepathSWA.setMinimumSize(QtCore.QSize(210, 0))
        self.lblOutputFilepathSWA.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblOutputFilepathSWA.setObjectName("lblOutputFilepathSWA")
        self.horizontalLayout_6.addWidget(self.lblOutputFilepathSWA)
        self.txtOutputFilepathSWA = QtWidgets.QLineEdit(self.grpSaveWithAxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtOutputFilepathSWA.sizePolicy().hasHeightForWidth())
        self.txtOutputFilepathSWA.setSizePolicy(sizePolicy)
        self.txtOutputFilepathSWA.setMinimumSize(QtCore.QSize(275, 31))
        self.txtOutputFilepathSWA.setObjectName("txtOutputFilepathSWA")
        self.horizontalLayout_6.addWidget(self.txtOutputFilepathSWA)
        self.btnOutputSelectSWA = QtWidgets.QPushButton(self.grpSaveWithAxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutputSelectSWA.sizePolicy().hasHeightForWidth())
        self.btnOutputSelectSWA.setSizePolicy(sizePolicy)
        self.btnOutputSelectSWA.setMinimumSize(QtCore.QSize(100, 33))
        self.btnOutputSelectSWA.setMaximumSize(QtCore.QSize(100, 33))
        self.btnOutputSelectSWA.setObjectName("btnOutputSelectSWA")
        self.horizontalLayout_6.addWidget(self.btnOutputSelectSWA)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.btnRunSWA = QtWidgets.QPushButton(self.grpSaveWithAxes)
        self.btnRunSWA.setObjectName("btnRunSWA")
        self.horizontalLayout_7.addWidget(self.btnRunSWA)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.grpSaveWithAxes)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lblOutputFilepathRadial = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOutputFilepathRadial.sizePolicy().hasHeightForWidth())
        self.lblOutputFilepathRadial.setSizePolicy(sizePolicy)
        self.lblOutputFilepathRadial.setMinimumSize(QtCore.QSize(210, 0))
        self.lblOutputFilepathRadial.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblOutputFilepathRadial.setObjectName("lblOutputFilepathRadial")
        self.horizontalLayout_10.addWidget(self.lblOutputFilepathRadial)
        self.txtOutputFilepathRadial = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtOutputFilepathRadial.sizePolicy().hasHeightForWidth())
        self.txtOutputFilepathRadial.setSizePolicy(sizePolicy)
        self.txtOutputFilepathRadial.setMinimumSize(QtCore.QSize(275, 31))
        self.txtOutputFilepathRadial.setObjectName("txtOutputFilepathRadial")
        self.horizontalLayout_10.addWidget(self.txtOutputFilepathRadial)
        self.btnOutputSelectRadial = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutputSelectRadial.sizePolicy().hasHeightForWidth())
        self.btnOutputSelectRadial.setSizePolicy(sizePolicy)
        self.btnOutputSelectRadial.setMinimumSize(QtCore.QSize(100, 33))
        self.btnOutputSelectRadial.setObjectName("btnOutputSelectRadial")
        self.horizontalLayout_10.addWidget(self.btnOutputSelectRadial)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lblRadialCentreX = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRadialCentreX.sizePolicy().hasHeightForWidth())
        self.lblRadialCentreX.setSizePolicy(sizePolicy)
        self.lblRadialCentreX.setMinimumSize(QtCore.QSize(25, 0))
        self.lblRadialCentreX.setObjectName("lblRadialCentreX")
        self.horizontalLayout_11.addWidget(self.lblRadialCentreX)
        self.spnRadialCentreX = QtWidgets.QSpinBox(self.groupBox_2)
        self.spnRadialCentreX.setMaximum(999)
        self.spnRadialCentreX.setProperty("value", 100)
        self.spnRadialCentreX.setObjectName("spnRadialCentreX")
        self.horizontalLayout_11.addWidget(self.spnRadialCentreX)
        self.lblRadialCentreY = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRadialCentreY.sizePolicy().hasHeightForWidth())
        self.lblRadialCentreY.setSizePolicy(sizePolicy)
        self.lblRadialCentreY.setMinimumSize(QtCore.QSize(25, 0))
        self.lblRadialCentreY.setObjectName("lblRadialCentreY")
        self.horizontalLayout_11.addWidget(self.lblRadialCentreY)
        self.spnRadialCentreY = QtWidgets.QSpinBox(self.groupBox_2)
        self.spnRadialCentreY.setMaximum(999)
        self.spnRadialCentreY.setProperty("value", 100)
        self.spnRadialCentreY.setObjectName("spnRadialCentreY")
        self.horizontalLayout_11.addWidget(self.spnRadialCentreY)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.btnRunRadialProfile = QtWidgets.QPushButton(self.groupBox)
        self.btnRunRadialProfile.setObjectName("btnRunRadialProfile")
        self.horizontalLayout_8.addWidget(self.btnRunRadialProfile)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_3.addWidget(self.btnClose)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Analysis"))
        self.lblScanDataFilepath.setText(_translate("MainWindow", "Scan data filepath"))
        self.btnScanDataSelect.setText(_translate("MainWindow", "Select"))
        self.grpBackgroundSubtraction.setTitle(_translate("MainWindow", "Background subtraction"))
        self.lblOutputFilepath.setText(_translate("MainWindow", "Output filepath"))
        self.btnOutputSelect.setText(_translate("MainWindow", "Select"))
        self.btnRun.setText(_translate("MainWindow", "Run"))
        self.grpSaveWithAxes.setTitle(_translate("MainWindow", "Save images with axes"))
        self.lblOutputFilepathSWA.setText(_translate("MainWindow", "Output filepath"))
        self.btnOutputSelectSWA.setText(_translate("MainWindow", "Select"))
        self.btnRunSWA.setText(_translate("MainWindow", "Run"))
        self.groupBox.setTitle(_translate("MainWindow", "Radial Profile"))
        self.lblOutputFilepathRadial.setText(_translate("MainWindow", "Output filepath"))
        self.btnOutputSelectRadial.setText(_translate("MainWindow", "Select"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Centre of radial profile"))
        self.lblRadialCentreX.setText(_translate("MainWindow", "X"))
        self.lblRadialCentreY.setText(_translate("MainWindow", "Y"))
        self.btnRunRadialProfile.setText(_translate("MainWindow", "Run"))
        self.btnClose.setText(_translate("MainWindow", "Close"))

