# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParticleScanAnalysisWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grpBackgroundSubtraction = QtWidgets.QGroupBox(self.centralwidget)
        self.grpBackgroundSubtraction.setObjectName("grpBackgroundSubtraction")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grpBackgroundSubtraction)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblScanDataFilepath = QtWidgets.QLabel(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScanDataFilepath.sizePolicy().hasHeightForWidth())
        self.lblScanDataFilepath.setSizePolicy(sizePolicy)
        self.lblScanDataFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblScanDataFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblScanDataFilepath.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.lblScanDataFilepath.setScaledContents(False)
        self.lblScanDataFilepath.setWordWrap(False)
        self.lblScanDataFilepath.setObjectName("lblScanDataFilepath")
        self.horizontalLayout_2.addWidget(self.lblScanDataFilepath)
        self.txtScanDataFilepath = QtWidgets.QLineEdit(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtScanDataFilepath.sizePolicy().hasHeightForWidth())
        self.txtScanDataFilepath.setSizePolicy(sizePolicy)
        self.txtScanDataFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtScanDataFilepath.setObjectName("txtScanDataFilepath")
        self.horizontalLayout_2.addWidget(self.txtScanDataFilepath)
        self.btnScanDataSelect = QtWidgets.QPushButton(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScanDataSelect.sizePolicy().hasHeightForWidth())
        self.btnScanDataSelect.setSizePolicy(sizePolicy)
        self.btnScanDataSelect.setMinimumSize(QtCore.QSize(100, 33))
        self.btnScanDataSelect.setMaximumSize(QtCore.QSize(100, 33))
        self.btnScanDataSelect.setObjectName("btnScanDataSelect")
        self.horizontalLayout_2.addWidget(self.btnScanDataSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblOutputFilepath = QtWidgets.QLabel(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOutputFilepath.sizePolicy().hasHeightForWidth())
        self.lblOutputFilepath.setSizePolicy(sizePolicy)
        self.lblOutputFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblOutputFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblOutputFilepath.setObjectName("lblOutputFilepath")
        self.horizontalLayout_4.addWidget(self.lblOutputFilepath)
        self.txtOutputFilepath = QtWidgets.QLineEdit(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtOutputFilepath.sizePolicy().hasHeightForWidth())
        self.txtOutputFilepath.setSizePolicy(sizePolicy)
        self.txtOutputFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtOutputFilepath.setObjectName("txtOutputFilepath")
        self.horizontalLayout_4.addWidget(self.txtOutputFilepath)
        self.btnOutputSelect = QtWidgets.QPushButton(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutputSelect.sizePolicy().hasHeightForWidth())
        self.btnOutputSelect.setSizePolicy(sizePolicy)
        self.btnOutputSelect.setMinimumSize(QtCore.QSize(100, 33))
        self.btnOutputSelect.setMaximumSize(QtCore.QSize(100, 33))
        self.btnOutputSelect.setObjectName("btnOutputSelect")
        self.horizontalLayout_4.addWidget(self.btnOutputSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnRun = QtWidgets.QPushButton(self.grpBackgroundSubtraction)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout.addWidget(self.btnRun)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.grpBackgroundSubtraction)
        self.grpSaveWithAxes = QtWidgets.QGroupBox(self.centralwidget)
        self.grpSaveWithAxes.setObjectName("grpSaveWithAxes")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.grpSaveWithAxes)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblScanDataFilepathSWA = QtWidgets.QLabel(self.grpSaveWithAxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScanDataFilepathSWA.sizePolicy().hasHeightForWidth())
        self.lblScanDataFilepathSWA.setSizePolicy(sizePolicy)
        self.lblScanDataFilepathSWA.setMinimumSize(QtCore.QSize(300, 0))
        self.lblScanDataFilepathSWA.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblScanDataFilepathSWA.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.lblScanDataFilepathSWA.setScaledContents(False)
        self.lblScanDataFilepathSWA.setWordWrap(False)
        self.lblScanDataFilepathSWA.setObjectName("lblScanDataFilepathSWA")
        self.horizontalLayout_5.addWidget(self.lblScanDataFilepathSWA)
        self.txtScanDataFilepathSWA = QtWidgets.QLineEdit(self.grpSaveWithAxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtScanDataFilepathSWA.sizePolicy().hasHeightForWidth())
        self.txtScanDataFilepathSWA.setSizePolicy(sizePolicy)
        self.txtScanDataFilepathSWA.setMinimumSize(QtCore.QSize(275, 31))
        self.txtScanDataFilepathSWA.setObjectName("txtScanDataFilepathSWA")
        self.horizontalLayout_5.addWidget(self.txtScanDataFilepathSWA)
        self.btnScanDataSelectSWA = QtWidgets.QPushButton(self.grpSaveWithAxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScanDataSelectSWA.sizePolicy().hasHeightForWidth())
        self.btnScanDataSelectSWA.setSizePolicy(sizePolicy)
        self.btnScanDataSelectSWA.setMinimumSize(QtCore.QSize(100, 33))
        self.btnScanDataSelectSWA.setMaximumSize(QtCore.QSize(100, 33))
        self.btnScanDataSelectSWA.setObjectName("btnScanDataSelectSWA")
        self.horizontalLayout_5.addWidget(self.btnScanDataSelectSWA)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblOutputFilepathSWA = QtWidgets.QLabel(self.grpSaveWithAxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOutputFilepathSWA.sizePolicy().hasHeightForWidth())
        self.lblOutputFilepathSWA.setSizePolicy(sizePolicy)
        self.lblOutputFilepathSWA.setMinimumSize(QtCore.QSize(300, 0))
        self.lblOutputFilepathSWA.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblOutputFilepathSWA.setObjectName("lblOutputFilepathSWA")
        self.horizontalLayout_6.addWidget(self.lblOutputFilepathSWA)
        self.txtOutputFilepathSWA = QtWidgets.QLineEdit(self.grpSaveWithAxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtOutputFilepathSWA.sizePolicy().hasHeightForWidth())
        self.txtOutputFilepathSWA.setSizePolicy(sizePolicy)
        self.txtOutputFilepathSWA.setMinimumSize(QtCore.QSize(275, 31))
        self.txtOutputFilepathSWA.setObjectName("txtOutputFilepathSWA")
        self.horizontalLayout_6.addWidget(self.txtOutputFilepathSWA)
        self.btnOutputSelectSWA = QtWidgets.QPushButton(self.grpSaveWithAxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutputSelectSWA.sizePolicy().hasHeightForWidth())
        self.btnOutputSelectSWA.setSizePolicy(sizePolicy)
        self.btnOutputSelectSWA.setMinimumSize(QtCore.QSize(100, 33))
        self.btnOutputSelectSWA.setMaximumSize(QtCore.QSize(100, 33))
        self.btnOutputSelectSWA.setObjectName("btnOutputSelectSWA")
        self.horizontalLayout_6.addWidget(self.btnOutputSelectSWA)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.btnRunSWA = QtWidgets.QPushButton(self.grpSaveWithAxes)
        self.btnRunSWA.setObjectName("btnRunSWA")
        self.horizontalLayout_7.addWidget(self.btnRunSWA)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.grpSaveWithAxes)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_3.addWidget(self.btnClose)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Analysis"))
        self.grpBackgroundSubtraction.setTitle(_translate("MainWindow", "Background subtraction"))
        self.lblScanDataFilepath.setText(_translate("MainWindow", "Scan data filepath"))
        self.btnScanDataSelect.setText(_translate("MainWindow", "Select"))
        self.lblOutputFilepath.setText(_translate("MainWindow", "Output filepath"))
        self.btnOutputSelect.setText(_translate("MainWindow", "Select"))
        self.btnRun.setText(_translate("MainWindow", "Run"))
        self.grpSaveWithAxes.setTitle(_translate("MainWindow", "Save images with axes"))
        self.lblScanDataFilepathSWA.setText(_translate("MainWindow", "Scan data filepath (processed)"))
        self.btnScanDataSelectSWA.setText(_translate("MainWindow", "Select"))
        self.lblOutputFilepathSWA.setText(_translate("MainWindow", "Output filepath"))
        self.btnOutputSelectSWA.setText(_translate("MainWindow", "Select"))
        self.btnRunSWA.setText(_translate("MainWindow", "Run"))
        self.btnClose.setText(_translate("MainWindow", "Close"))

