# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageAnalysisWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 1209)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grpBackgroundSubtraction = QtWidgets.QGroupBox(self.centralwidget)
        self.grpBackgroundSubtraction.setObjectName("grpBackgroundSubtraction")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.grpBackgroundSubtraction)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblBackgroundFilepath = QtWidgets.QLabel(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBackgroundFilepath.sizePolicy().hasHeightForWidth())
        self.lblBackgroundFilepath.setSizePolicy(sizePolicy)
        self.lblBackgroundFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblBackgroundFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblBackgroundFilepath.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.lblBackgroundFilepath.setScaledContents(False)
        self.lblBackgroundFilepath.setWordWrap(False)
        self.lblBackgroundFilepath.setObjectName("lblBackgroundFilepath")
        self.horizontalLayout_2.addWidget(self.lblBackgroundFilepath)
        self.txtBackgroundFilepath = QtWidgets.QLineEdit(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBackgroundFilepath.sizePolicy().hasHeightForWidth())
        self.txtBackgroundFilepath.setSizePolicy(sizePolicy)
        self.txtBackgroundFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtBackgroundFilepath.setObjectName("txtBackgroundFilepath")
        self.horizontalLayout_2.addWidget(self.txtBackgroundFilepath)
        self.btnBackgroundSelect = QtWidgets.QPushButton(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBackgroundSelect.sizePolicy().hasHeightForWidth())
        self.btnBackgroundSelect.setSizePolicy(sizePolicy)
        self.btnBackgroundSelect.setMinimumSize(QtCore.QSize(100, 33))
        self.btnBackgroundSelect.setMaximumSize(QtCore.QSize(100, 33))
        self.btnBackgroundSelect.setObjectName("btnBackgroundSelect")
        self.horizontalLayout_2.addWidget(self.btnBackgroundSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblImageFilepath = QtWidgets.QLabel(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImageFilepath.sizePolicy().hasHeightForWidth())
        self.lblImageFilepath.setSizePolicy(sizePolicy)
        self.lblImageFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblImageFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblImageFilepath.setObjectName("lblImageFilepath")
        self.horizontalLayout_3.addWidget(self.lblImageFilepath)
        self.txtImageFilepath = QtWidgets.QLineEdit(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtImageFilepath.sizePolicy().hasHeightForWidth())
        self.txtImageFilepath.setSizePolicy(sizePolicy)
        self.txtImageFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtImageFilepath.setObjectName("txtImageFilepath")
        self.horizontalLayout_3.addWidget(self.txtImageFilepath)
        self.btnImageSelect = QtWidgets.QPushButton(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImageSelect.sizePolicy().hasHeightForWidth())
        self.btnImageSelect.setSizePolicy(sizePolicy)
        self.btnImageSelect.setMinimumSize(QtCore.QSize(100, 33))
        self.btnImageSelect.setMaximumSize(QtCore.QSize(100, 33))
        self.btnImageSelect.setObjectName("btnImageSelect")
        self.horizontalLayout_3.addWidget(self.btnImageSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblOutputFilepath = QtWidgets.QLabel(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOutputFilepath.sizePolicy().hasHeightForWidth())
        self.lblOutputFilepath.setSizePolicy(sizePolicy)
        self.lblOutputFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblOutputFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblOutputFilepath.setObjectName("lblOutputFilepath")
        self.horizontalLayout_4.addWidget(self.lblOutputFilepath)
        self.txtOutputFilepath = QtWidgets.QLineEdit(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtOutputFilepath.sizePolicy().hasHeightForWidth())
        self.txtOutputFilepath.setSizePolicy(sizePolicy)
        self.txtOutputFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtOutputFilepath.setObjectName("txtOutputFilepath")
        self.horizontalLayout_4.addWidget(self.txtOutputFilepath)
        self.btnOutputSelect = QtWidgets.QPushButton(self.grpBackgroundSubtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutputSelect.sizePolicy().hasHeightForWidth())
        self.btnOutputSelect.setSizePolicy(sizePolicy)
        self.btnOutputSelect.setMinimumSize(QtCore.QSize(100, 33))
        self.btnOutputSelect.setMaximumSize(QtCore.QSize(100, 33))
        self.btnOutputSelect.setObjectName("btnOutputSelect")
        self.horizontalLayout_4.addWidget(self.btnOutputSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnRun = QtWidgets.QPushButton(self.grpBackgroundSubtraction)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout.addWidget(self.btnRun)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.grpBackgroundSubtraction)
        self.grpCropping = QtWidgets.QGroupBox(self.centralwidget)
        self.grpCropping.setObjectName("grpCropping")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.grpCropping)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lblCropImageFilepath = QtWidgets.QLabel(self.grpCropping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCropImageFilepath.sizePolicy().hasHeightForWidth())
        self.lblCropImageFilepath.setSizePolicy(sizePolicy)
        self.lblCropImageFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblCropImageFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblCropImageFilepath.setObjectName("lblCropImageFilepath")
        self.horizontalLayout_10.addWidget(self.lblCropImageFilepath)
        self.txtCropImageFilepath = QtWidgets.QLineEdit(self.grpCropping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCropImageFilepath.sizePolicy().hasHeightForWidth())
        self.txtCropImageFilepath.setSizePolicy(sizePolicy)
        self.txtCropImageFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtCropImageFilepath.setObjectName("txtCropImageFilepath")
        self.horizontalLayout_10.addWidget(self.txtCropImageFilepath)
        self.btnCropImageFilepath = QtWidgets.QPushButton(self.grpCropping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCropImageFilepath.sizePolicy().hasHeightForWidth())
        self.btnCropImageFilepath.setSizePolicy(sizePolicy)
        self.btnCropImageFilepath.setMinimumSize(QtCore.QSize(100, 33))
        self.btnCropImageFilepath.setMaximumSize(QtCore.QSize(100, 33))
        self.btnCropImageFilepath.setObjectName("btnCropImageFilepath")
        self.horizontalLayout_10.addWidget(self.btnCropImageFilepath)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lblCropOutputFilepath = QtWidgets.QLabel(self.grpCropping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCropOutputFilepath.sizePolicy().hasHeightForWidth())
        self.lblCropOutputFilepath.setSizePolicy(sizePolicy)
        self.lblCropOutputFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblCropOutputFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblCropOutputFilepath.setObjectName("lblCropOutputFilepath")
        self.horizontalLayout_11.addWidget(self.lblCropOutputFilepath)
        self.txtCropOutputFilepath = QtWidgets.QLineEdit(self.grpCropping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCropOutputFilepath.sizePolicy().hasHeightForWidth())
        self.txtCropOutputFilepath.setSizePolicy(sizePolicy)
        self.txtCropOutputFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtCropOutputFilepath.setObjectName("txtCropOutputFilepath")
        self.horizontalLayout_11.addWidget(self.txtCropOutputFilepath)
        self.btnCropOutputFilepath = QtWidgets.QPushButton(self.grpCropping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCropOutputFilepath.sizePolicy().hasHeightForWidth())
        self.btnCropOutputFilepath.setSizePolicy(sizePolicy)
        self.btnCropOutputFilepath.setMinimumSize(QtCore.QSize(100, 33))
        self.btnCropOutputFilepath.setMaximumSize(QtCore.QSize(100, 33))
        self.btnCropOutputFilepath.setObjectName("btnCropOutputFilepath")
        self.horizontalLayout_11.addWidget(self.btnCropOutputFilepath)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.grpMargins = QtWidgets.QGroupBox(self.grpCropping)
        self.grpMargins.setObjectName("grpMargins")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.grpMargins)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lblLeftMargin = QtWidgets.QLabel(self.grpMargins)
        self.lblLeftMargin.setObjectName("lblLeftMargin")
        self.horizontalLayout_13.addWidget(self.lblLeftMargin)
        self.spinboxLeftMargin = QtWidgets.QSpinBox(self.grpMargins)
        self.spinboxLeftMargin.setMaximum(9999)
        self.spinboxLeftMargin.setObjectName("spinboxLeftMargin")
        self.horizontalLayout_13.addWidget(self.spinboxLeftMargin)
        self.lblRightMargin = QtWidgets.QLabel(self.grpMargins)
        self.lblRightMargin.setObjectName("lblRightMargin")
        self.horizontalLayout_13.addWidget(self.lblRightMargin)
        self.spinboxRightMargin = QtWidgets.QSpinBox(self.grpMargins)
        self.spinboxRightMargin.setMaximum(9999)
        self.spinboxRightMargin.setObjectName("spinboxRightMargin")
        self.horizontalLayout_13.addWidget(self.spinboxRightMargin)
        self.lblTopMargin = QtWidgets.QLabel(self.grpMargins)
        self.lblTopMargin.setObjectName("lblTopMargin")
        self.horizontalLayout_13.addWidget(self.lblTopMargin)
        self.spinboxTopMargin = QtWidgets.QSpinBox(self.grpMargins)
        self.spinboxTopMargin.setMaximum(9999)
        self.spinboxTopMargin.setObjectName("spinboxTopMargin")
        self.horizontalLayout_13.addWidget(self.spinboxTopMargin)
        self.lblBottomMargin = QtWidgets.QLabel(self.grpMargins)
        self.lblBottomMargin.setObjectName("lblBottomMargin")
        self.horizontalLayout_13.addWidget(self.lblBottomMargin)
        self.spinboxBottomMargin = QtWidgets.QSpinBox(self.grpMargins)
        self.spinboxBottomMargin.setMaximum(9999)
        self.spinboxBottomMargin.setObjectName("spinboxBottomMargin")
        self.horizontalLayout_13.addWidget(self.spinboxBottomMargin)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.verticalLayout_7.addWidget(self.grpMargins)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.btnCropRun = QtWidgets.QPushButton(self.grpCropping)
        self.btnCropRun.setObjectName("btnCropRun")
        self.horizontalLayout_14.addWidget(self.btnCropRun)
        self.btnCropSave = QtWidgets.QPushButton(self.grpCropping)
        self.btnCropSave.setObjectName("btnCropSave")
        self.horizontalLayout_14.addWidget(self.btnCropSave)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addWidget(self.grpCropping, 0, QtCore.Qt.AlignLeft)
        self.grpCrossSectioning = QtWidgets.QGroupBox(self.centralwidget)
        self.grpCrossSectioning.setObjectName("grpCrossSectioning")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.grpCrossSectioning)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblCrossSectionFilepath = QtWidgets.QLabel(self.grpCrossSectioning)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCrossSectionFilepath.sizePolicy().hasHeightForWidth())
        self.lblCrossSectionFilepath.setSizePolicy(sizePolicy)
        self.lblCrossSectionFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblCrossSectionFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblCrossSectionFilepath.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.lblCrossSectionFilepath.setScaledContents(False)
        self.lblCrossSectionFilepath.setWordWrap(False)
        self.lblCrossSectionFilepath.setObjectName("lblCrossSectionFilepath")
        self.horizontalLayout_5.addWidget(self.lblCrossSectionFilepath)
        self.txtCrossSectionFilepath = QtWidgets.QLineEdit(self.grpCrossSectioning)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCrossSectionFilepath.sizePolicy().hasHeightForWidth())
        self.txtCrossSectionFilepath.setSizePolicy(sizePolicy)
        self.txtCrossSectionFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtCrossSectionFilepath.setObjectName("txtCrossSectionFilepath")
        self.horizontalLayout_5.addWidget(self.txtCrossSectionFilepath)
        self.btnCrossSectionSelect = QtWidgets.QPushButton(self.grpCrossSectioning)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCrossSectionSelect.sizePolicy().hasHeightForWidth())
        self.btnCrossSectionSelect.setSizePolicy(sizePolicy)
        self.btnCrossSectionSelect.setMinimumSize(QtCore.QSize(100, 33))
        self.btnCrossSectionSelect.setMaximumSize(QtCore.QSize(100, 33))
        self.btnCrossSectionSelect.setObjectName("btnCrossSectionSelect")
        self.horizontalLayout_5.addWidget(self.btnCrossSectionSelect)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblCrossSectionOutputFilepath = QtWidgets.QLabel(self.grpCrossSectioning)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCrossSectionOutputFilepath.sizePolicy().hasHeightForWidth())
        self.lblCrossSectionOutputFilepath.setSizePolicy(sizePolicy)
        self.lblCrossSectionOutputFilepath.setMinimumSize(QtCore.QSize(210, 0))
        self.lblCrossSectionOutputFilepath.setMaximumSize(QtCore.QSize(210, 16777215))
        self.lblCrossSectionOutputFilepath.setObjectName("lblCrossSectionOutputFilepath")
        self.horizontalLayout_9.addWidget(self.lblCrossSectionOutputFilepath)
        self.txtCrossSectionOutputFilepath = QtWidgets.QLineEdit(self.grpCrossSectioning)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCrossSectionOutputFilepath.sizePolicy().hasHeightForWidth())
        self.txtCrossSectionOutputFilepath.setSizePolicy(sizePolicy)
        self.txtCrossSectionOutputFilepath.setMinimumSize(QtCore.QSize(275, 31))
        self.txtCrossSectionOutputFilepath.setObjectName("txtCrossSectionOutputFilepath")
        self.horizontalLayout_9.addWidget(self.txtCrossSectionOutputFilepath)
        self.btnCrossSectionOutputSelect = QtWidgets.QPushButton(self.grpCrossSectioning)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCrossSectionOutputSelect.sizePolicy().hasHeightForWidth())
        self.btnCrossSectionOutputSelect.setSizePolicy(sizePolicy)
        self.btnCrossSectionOutputSelect.setMinimumSize(QtCore.QSize(100, 33))
        self.btnCrossSectionOutputSelect.setObjectName("btnCrossSectionOutputSelect")
        self.horizontalLayout_9.addWidget(self.btnCrossSectionOutputSelect)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblCutAxis = QtWidgets.QLabel(self.grpCrossSectioning)
        self.lblCutAxis.setObjectName("lblCutAxis")
        self.horizontalLayout_6.addWidget(self.lblCutAxis)
        self.radioX = QtWidgets.QRadioButton(self.grpCrossSectioning)
        self.radioX.setObjectName("radioX")
        self.horizontalLayout_6.addWidget(self.radioX)
        self.radioY = QtWidgets.QRadioButton(self.grpCrossSectioning)
        self.radioY.setChecked(True)
        self.radioY.setObjectName("radioY")
        self.horizontalLayout_6.addWidget(self.radioY)
        self.lblCutPosition = QtWidgets.QLabel(self.grpCrossSectioning)
        self.lblCutPosition.setObjectName("lblCutPosition")
        self.horizontalLayout_6.addWidget(self.lblCutPosition)
        self.spinboxCutPosition = QtWidgets.QSpinBox(self.grpCrossSectioning)
        self.spinboxCutPosition.setMaximum(99999)
        self.spinboxCutPosition.setProperty("value", 0)
        self.spinboxCutPosition.setObjectName("spinboxCutPosition")
        self.horizontalLayout_6.addWidget(self.spinboxCutPosition)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.btnRunCrossSection = QtWidgets.QPushButton(self.grpCrossSectioning)
        self.btnRunCrossSection.setObjectName("btnRunCrossSection")
        self.horizontalLayout_8.addWidget(self.btnRunCrossSection)
        self.btnSaveCrossSection = QtWidgets.QPushButton(self.grpCrossSectioning)
        self.btnSaveCrossSection.setObjectName("btnSaveCrossSection")
        self.horizontalLayout_8.addWidget(self.btnSaveCrossSection)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.grpCrossSectioning)
        self.grpDisplay = QtWidgets.QGroupBox(self.centralwidget)
        self.grpDisplay.setToolTipDuration(0)
        self.grpDisplay.setObjectName("grpDisplay")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.grpDisplay)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widgetDisplay = MatplotlibWidget(self.grpDisplay)
        self.widgetDisplay.setMinimumSize(QtCore.QSize(0, 300))
        self.widgetDisplay.setObjectName("widgetDisplay")
        self.verticalLayout_6.addWidget(self.widgetDisplay)
        self.verticalLayout_2.addWidget(self.grpDisplay)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_7.addWidget(self.btnClose)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Analysis"))
        self.grpBackgroundSubtraction.setTitle(_translate("MainWindow", "Background Subtraction"))
        self.lblBackgroundFilepath.setText(_translate("MainWindow", "Background filepath"))
        self.btnBackgroundSelect.setText(_translate("MainWindow", "Select"))
        self.lblImageFilepath.setText(_translate("MainWindow", "Data image filepath"))
        self.btnImageSelect.setText(_translate("MainWindow", "Select"))
        self.lblOutputFilepath.setText(_translate("MainWindow", "Output filepath"))
        self.btnOutputSelect.setText(_translate("MainWindow", "Select"))
        self.btnRun.setText(_translate("MainWindow", "Run"))
        self.grpCropping.setTitle(_translate("MainWindow", "Cropping"))
        self.lblCropImageFilepath.setText(_translate("MainWindow", "Image Filepath"))
        self.btnCropImageFilepath.setText(_translate("MainWindow", "Select"))
        self.lblCropOutputFilepath.setText(_translate("MainWindow", "Output Filepath"))
        self.btnCropOutputFilepath.setText(_translate("MainWindow", "Select"))
        self.grpMargins.setTitle(_translate("MainWindow", "Crop Margins"))
        self.lblLeftMargin.setText(_translate("MainWindow", "Left"))
        self.lblRightMargin.setText(_translate("MainWindow", "Right"))
        self.lblTopMargin.setText(_translate("MainWindow", "Top"))
        self.lblBottomMargin.setText(_translate("MainWindow", "Bottom"))
        self.btnCropRun.setText(_translate("MainWindow", "Run"))
        self.btnCropSave.setText(_translate("MainWindow", "Save"))
        self.grpCrossSectioning.setTitle(_translate("MainWindow", "Cross Sectioning"))
        self.lblCrossSectionFilepath.setText(_translate("MainWindow", "Image filepath"))
        self.btnCrossSectionSelect.setText(_translate("MainWindow", "Select"))
        self.lblCrossSectionOutputFilepath.setText(_translate("MainWindow", "Output filepath"))
        self.btnCrossSectionOutputSelect.setText(_translate("MainWindow", "Select"))
        self.lblCutAxis.setText(_translate("MainWindow", "Axis to cut along:"))
        self.radioX.setText(_translate("MainWindow", "X"))
        self.radioY.setText(_translate("MainWindow", "Y"))
        self.lblCutPosition.setText(_translate("MainWindow", "Position of cut:"))
        self.btnRunCrossSection.setText(_translate("MainWindow", "Run"))
        self.btnSaveCrossSection.setText(_translate("MainWindow", "Save"))
        self.grpDisplay.setTitle(_translate("MainWindow", "Display"))
        self.btnClose.setText(_translate("MainWindow", "Close"))

from matplotlibwidget import MatplotlibWidget
